/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.shop.system.nb.Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import pet.shop.system.nb.Connect;
import pet.shop.system.nb.Enum.Enum_Species;
import pet.shop.system.nb.Vet;

/**
 *
 * @author User
 */
public class Frame_Vet extends javax.swing.JFrame {
private Connection conn=null;
private PreparedStatement pst=null;
private ResultSet rs=null;
private Vet vet;
    /**
     * Creates new form Frame_Vet
     */
    public Frame_Vet() {
        initComponents();
    }
    
    public Frame_Vet(Vet vet) {
        initComponents();
        this.vet=vet;      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_vet = new javax.swing.JTable();
        btn_consult = new javax.swing.JButton();
        btn_view_status = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_vet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID","Date","Start Time","End Time", "Pet Name", "Species"
            }
        ));
        jTable_vet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_vetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_vet);

        btn_consult.setText("Consult pet");
        btn_consult.setEnabled(false);
        btn_consult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultMouseClicked(evt);
            }
        });

        btn_view_status.setText("View boarding service pet status");
        btn_view_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_statusMouseClicked(evt);
            }
        });

        jLabel1.setText("Today's appointment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_consult, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_view_status, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consult)
                    .addComponent(btn_view_status))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_vetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_vetMouseClicked
        btn_consult.setEnabled(true);
    }//GEN-LAST:event_jTable_vetMouseClicked

    private void btn_consultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultMouseClicked
        int row=jTable_vet.getSelectedRow();
        Enum_Species species=Enum_Species.valueOf(jTable_vet.getModel().getValueAt(row, 5).toString());
        vet.petHealthReport(species);
    }//GEN-LAST:event_btn_consultMouseClicked

    private void btn_view_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_statusMouseClicked
        Frame_Vet_View_Pet_Status fr= new Frame_Vet_View_Pet_Status();
        fr.setVisible(true);
    }//GEN-LAST:event_btn_view_statusMouseClicked

    public void updateJTable(){  
        String sql="SELECT ID,appointment_date,appointment_time_start,appointment_time_end,pet_name,pet_species FROM AppointmentTable"
                + "WHERE vet_name="+vet.getName();
        conn=Connect.connectDB();
        try{
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            jTable_vet.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Vet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Vet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Vet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Vet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Vet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consult;
    private javax.swing.JButton btn_view_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_vet;
    // End of variables declaration//GEN-END:variables
}
