/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.shop.system.nb.Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import pet.shop.system.nb.Connect;
import pet.shop.system.nb.Receptionist;

/**
 *
 * @author User
 */
public class Frame_Receptionist extends javax.swing.JFrame {
private static Connection conn=null;
private static PreparedStatement pst=null;
private static ResultSet rs=null;
private Receptionist receptionist;
    /**
     * Creates new form Frame_Receptionist
     */
    public Frame_Receptionist(){
        initComponents();
        updateJTable(jTable_receptionist_appointment);
        updateJTable(jTable_receptionist_boarding);
    }
    
    public Frame_Receptionist(Receptionist receptionist) {
        initComponents();
        conn=Connect.connectDB();
        updateJTable(jTable_receptionist_appointment);
        updateJTable(jTable_receptionist_boarding);
        this.receptionist=receptionist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_appointment_new = new javax.swing.JButton();
        btn_appointment_edit = new javax.swing.JButton();
        btn_appointment_cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_receptionist_appointment = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_register_customer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_boardingService_new = new javax.swing.JButton();
        btn_boardingService_edit = new javax.swing.JButton();
        btn_boardingService_cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_receptionist_boarding = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_appointment_new.setText("New Appointment");
        btn_appointment_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_appointment_newMouseClicked(evt);
            }
        });

        btn_appointment_edit.setText("Edit Appointment");
        btn_appointment_edit.setEnabled(false);
        btn_appointment_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_appointment_editMouseClicked(evt);
            }
        });

        btn_appointment_cancel.setText("Cancel Appointment");
        btn_appointment_cancel.setEnabled(false);
        btn_appointment_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_appointment_cancelMouseClicked(evt);
            }
        });

        jTable_receptionist_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID","Date","Start Time","End Time", "Customer Name", "Pet Name", "Species","Vet"
            }
        ));
        jTable_receptionist_appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_receptionist_appointmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_receptionist_appointment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_appointment_new, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_appointment_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_appointment_cancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_appointment_new)
                    .addComponent(btn_appointment_edit)
                    .addComponent(btn_appointment_cancel))
                .addGap(22, 22, 22))
        );

        jTabbedPane4.addTab("Appointment ", jPanel1);

        btn_register_customer.setText("Register Member");
        btn_register_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_register_customerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btn_register_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btn_register_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Management", jPanel4);

        btn_boardingService_new.setText("New Boarding Service");
        btn_boardingService_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_boardingService_newMouseClicked(evt);
            }
        });

        btn_boardingService_edit.setText("Edit Boarding Service");
        btn_boardingService_edit.setEnabled(false);
        btn_boardingService_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_boardingService_editMouseClicked(evt);
            }
        });

        btn_boardingService_cancel.setText("Cancel Boarding Service");
        btn_boardingService_cancel.setEnabled(false);
        btn_boardingService_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_boardingService_cancelMouseClicked(evt);
            }
        });

        jTable_receptionist_boarding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Customer Name", "Pet Name", "Species"
            }
        ));
        jTable_receptionist_boarding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_receptionist_boardingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_receptionist_boarding);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_boardingService_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_boardingService_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_boardingService_cancel)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_boardingService_new)
                    .addComponent(btn_boardingService_edit)
                    .addComponent(btn_boardingService_cancel))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Boarding Service", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_register_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register_customerMouseClicked
        // TODO add your handling code here:
        Frame_Receptionist_Register_Customer frc=new Frame_Receptionist_Register_Customer();
        frc.setVisible(true);
    }//GEN-LAST:event_btn_register_customerMouseClicked

    private void jTable_receptionist_appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_receptionist_appointmentMouseClicked
        btn_appointment_edit.setEnabled(true);
        btn_appointment_cancel.setEnabled(true);
    }//GEN-LAST:event_jTable_receptionist_appointmentMouseClicked

    private void btn_appointment_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_appointment_cancelMouseClicked
        int row=jTable_receptionist_appointment.getSelectedRow();
        String id=jTable_receptionist_appointment.getModel().getValueAt(row, 0).toString();
        receptionist.cancelAppointment(id);
        updateJTable(jTable_receptionist_appointment);
    }//GEN-LAST:event_btn_appointment_cancelMouseClicked

    private void btn_appointment_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_appointment_editMouseClicked
        int row=jTable_receptionist_appointment.getSelectedRow();
        Frame_Receptionist_Create_Appointment fca=new Frame_Receptionist_Create_Appointment(this);
        String id=jTable_receptionist_appointment.getModel().getValueAt(row, 0).toString();
        fca.setID(id);
        fca.setVisible(true);
    }//GEN-LAST:event_btn_appointment_editMouseClicked

    private void btn_appointment_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_appointment_newMouseClicked
        // TODO add your handling code here:
        Frame_Receptionist_Create_Appointment fca=new Frame_Receptionist_Create_Appointment(this);
        fca.setVisible(true);
    }//GEN-LAST:event_btn_appointment_newMouseClicked

    private void btn_boardingService_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_boardingService_newMouseClicked
        Frame_Receptionist_Boarding_Service frbs=new Frame_Receptionist_Boarding_Service(this);
        frbs.setVisible(true);
    }//GEN-LAST:event_btn_boardingService_newMouseClicked

    private void btn_boardingService_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_boardingService_editMouseClicked
        int row=jTable_receptionist_boarding.getSelectedRow();
        Frame_Receptionist_Boarding_Service frbs=new Frame_Receptionist_Boarding_Service(this);
        String id=jTable_receptionist_boarding.getModel().getValueAt(row, 0).toString();
        frbs.setID(id);
        frbs.setVisible(true);
    }//GEN-LAST:event_btn_boardingService_editMouseClicked

    private void jTable_receptionist_boardingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_receptionist_boardingMouseClicked
        btn_boardingService_edit.setEnabled(true);
        btn_boardingService_cancel.setEnabled(true);
    }//GEN-LAST:event_jTable_receptionist_boardingMouseClicked

    private void btn_boardingService_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_boardingService_cancelMouseClicked
        int row=jTable_receptionist_boarding.getSelectedRow();
        String id=jTable_receptionist_boarding.getModel().getValueAt(row, 0).toString();
        receptionist.cancelBoarding(id);
        updateJTable(jTable_receptionist_boarding);
    }//GEN-LAST:event_btn_boardingService_cancelMouseClicked

    public JTable getJTable_Appointment(){
        return jTable_receptionist_appointment;
    }
    
    public JTable getJTable_Boarding(){
        return jTable_receptionist_boarding;
    }
    
    public void updateJTable(JTable jtable){  
        String sql="SELECT ID,appointment_date,appointment_time_start,appointment_time_end,cust_first_name,pet_name,pet_species,vet_name FROM AppointmentTable";
        String sql1="SELECT ID,appointment_date,cust_first_name,pet_name,pet_species FROM BoardingServiceTable";
        try{
            pst=(jtable==jTable_receptionist_appointment)?conn.prepareStatement(sql):conn.prepareStatement(sql1);
            rs= pst.executeQuery();
            jtable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments^
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_appointment_cancel;
    private javax.swing.JButton btn_appointment_edit;
    private javax.swing.JButton btn_appointment_new;
    private javax.swing.JButton btn_boardingService_cancel;
    private javax.swing.JButton btn_boardingService_edit;
    private javax.swing.JButton btn_boardingService_new;
    private javax.swing.JButton btn_register_customer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable_receptionist_appointment;
    private javax.swing.JTable jTable_receptionist_boarding;
    // End of variables declaration//GEN-END:variables
}
