/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.shop.system.nb.Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pet.shop.system.nb.Connect;
import pet.shop.system.nb.Customer_Member;
import pet.shop.system.nb.Enum.Enum_Domestic_Exotic;
import pet.shop.system.nb.Enum.Enum_Gender;
import pet.shop.system.nb.Enum.Enum_Species;

/**
 *
 * @author User
 */
public class Frame_Receptionist_Register_Pet extends javax.swing.JFrame {
private Connection conn=null;
private PreparedStatement pst=null;
private ResultSet rs=null;
private PreparedStatement pst1=null;
private ResultSet rs1=null;
private int id_member,id_pet;
private String firstName,lastName,address,email,contact,username,password;
private Customer_Member cm;
    /**
     * Creates new form Frame_Register_Pet
     */
    public Frame_Receptionist_Register_Pet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        et_pet_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        et_pet_age = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_pet_species = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cb_pet_gender = new javax.swing.JComboBox();
        btn_register_done = new javax.swing.JButton();
        cb_pet_domestic = new javax.swing.JCheckBox();
        cb_pet_exotic = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        et_pet_weight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel4.setText("Species");

        cb_pet_species.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dog", "Cat", "Rabbit", "Lizard","Bird" }));

        jLabel5.setText("Gender");

        cb_pet_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female"}));

        btn_register_done.setText("Done");
        btn_register_done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_register_doneMouseClicked(evt);
            }
        });

        cb_pet_domestic.setText("Domestic");

        cb_pet_exotic.setText("Exotic");

        jLabel6.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_register_done)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(et_pet_name, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(et_pet_age, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(et_pet_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_pet_domestic)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_pet_species, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_pet_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_pet_exotic))))
                        .addContainerGap(181, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(et_pet_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_pet_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(et_pet_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pet_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pet_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pet_domestic)
                    .addComponent(cb_pet_exotic))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_register_done)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_register_doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register_doneMouseClicked
        // TODO add your handling code here:
         cm= new Customer_Member(firstName,lastName,address,contact,email,username,password,
         et_pet_name.getText(),et_pet_age.getText(),et_pet_weight.getText(),Enum_Species.valueOf(cb_pet_species.getSelectedItem().toString()),
         Enum_Gender.valueOf(cb_pet_gender.getSelectedItem().toString()),Enum_Domestic_Exotic.Exotic);
         
         String sql1="SELECT TOP 1 ID FROM UserDetails ORDER BY ID DESC";
         String sql2="SELECT TOP 1 ID FROM PetDetails ORDER BY ID DESC";
            try{
                pst=conn.prepareStatement(sql1);
                rs=pst.executeQuery();
                pst1=conn.prepareStatement(sql2);
                rs1=pst.executeQuery();
                if(rs.next()){id_member=rs.getInt("ID");}
                if(rs.next()){id_pet=rs1.getInt("ID");}
            }catch(Exception e){
                
            }
            insertToTable();
    }//GEN-LAST:event_btn_register_doneMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn=Connect.connectDB();
    }//GEN-LAST:event_formWindowOpened

    public void memberData(String firstName,String lastName,String address, String contact, String email,String username,String password){
        this.firstName=firstName;
        this.lastName=lastName;
        this.address=address;
        this.contact=contact;
        this.email=email;
        this.username=username;
        this.password=password;
    }
    
    public void insertToTable(){
        id_member++;id_pet++;
        String sql1="INSERT INTO UserDetails VALUES("+
                        id_member+",'"+
                        cm.getUsername()+"','"+
                        cm.getPassword()+"','"+
                        "member"+"','"+
                        cm.getFirstName()+"','"+
                        cm.getLastName()+"','"+
                        cm.getContact()+"','"+
                        cm.getAddress()+"','"+
                        cm.getEmail()+"')";
        String sql2="INSERT INTO PetDetails VALUES("+
                        id_pet+",'"+
                        cm.getPetName()+"','"+
                        cm.getPetAge()+"','"+
                        cm.getPetWeight()+"','"+
                        cm.getPetDoe()+"','"+
                        cm.getPetSpecies()+"','"+
                        cm.getPetGender()+"')";
        
        try{
        pst=conn.prepareStatement(sql1);
        pst.execute();
        pst=conn.prepareStatement(sql2);
        pst.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Register_Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Register_Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Register_Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Register_Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Receptionist_Register_Pet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register_done;
    private javax.swing.JCheckBox cb_pet_domestic;
    private javax.swing.JCheckBox cb_pet_exotic;
    private javax.swing.JComboBox cb_pet_gender;
    private javax.swing.JComboBox cb_pet_species;
    private javax.swing.JTextField et_pet_age;
    private javax.swing.JTextField et_pet_name;
    private javax.swing.JTextField et_pet_weight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
