/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.shop.system.nb.Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import org.hsqldb.persist.Log;
import pet.shop.system.nb.Appointment;
import pet.shop.system.nb.Connect;
import pet.shop.system.nb.Enum.Enum_Domestic_Exotic;
import pet.shop.system.nb.Enum.Enum_Species;
/**
 *
 * @author User
 */
public class Frame_Receptionist_Create_Appointment extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
private SimpleDateFormat obDataFormat = new SimpleDateFormat("MMM dd yyyy");
private int id;
private String id_selected;
private boolean isEdit=false;
    /**
     * Creates new form Frame_CreateAppointment
     */
    public Frame_Receptionist_Create_Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        et_owner_first_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        et_owner_pet_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_vet = new javax.swing.JComboBox();
        cb_domestic = new javax.swing.JCheckBox();
        cb_exotic = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cb_time_start = new javax.swing.JComboBox();
        btn_done_appointment = new javax.swing.JButton();
        jdc_appointment = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        et_owner_last_name = new javax.swing.JTextField();
        et_owner_contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        et_owner_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        et_owner_address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_species = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cb_time_end = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        cb_pet_gender = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Owner First Name");

        jLabel6.setText("Date");

        jLabel8.setText("Pet name");

        jLabel9.setText("Vet");

        cb_vet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_domestic.setText("Domestic");

        cb_exotic.setText("Exotic");

        jLabel10.setText("Time");

        cb_time_start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10 am", "11 am", "12 pm", "1 pm","2 pm","3 pm","4 pm","5 pm","6 pm" }));

        btn_done_appointment.setText("Done");
        btn_done_appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_done_appointmentMouseClicked(evt);
            }
        });

        jdc_appointment.setDateFormatString("MMM d, yyy");

        jLabel3.setText("Owner Last Name");

        jLabel5.setText("Email");

        jLabel4.setText("Address");

        jLabel11.setText("Contact");

        jLabel12.setText("Species");

        cb_species.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dog", "Cat", "Rabbit", "Lizard","Bird" }));

        jLabel13.setText("Start: ");

        jLabel14.setText("End:");

        cb_time_end.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11 am", "12 pm", "1 pm", "2 pm","3 pm","4 pm","5 pm","6 pm","7 pm" }));

        jCheckBox1.setText("Member");

        cb_pet_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male","Female" }));

        jLabel15.setText("Gender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addGap(40, 40, 40))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(et_owner_contact)
                    .addComponent(et_owner_last_name)
                    .addComponent(et_owner_first_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(et_owner_email)
                    .addComponent(et_owner_pet_name)
                    .addComponent(et_owner_address, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_domestic)
                        .addGap(18, 18, 18)
                        .addComponent(cb_exotic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                    .addComponent(cb_species, 0, 268, Short.MAX_VALUE)
                    .addComponent(cb_pet_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_vet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdc_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_time_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_time_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_done_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(et_owner_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(et_owner_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(et_owner_address, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(et_owner_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(et_owner_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(et_owner_pet_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb_domestic)
                                    .addComponent(cb_exotic))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cb_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(btn_done_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cb_vet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jdc_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cb_time_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(cb_time_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cb_pet_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(390, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_done_appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_done_appointmentMouseClicked
        if(isEdit==true){
            if(cb_domestic.isSelected()){
            String sql="Update AppointmentTable set cust_first_name="+et_owner_first_name.getText()+
                    "cust_last_name="+et_owner_last_name.getText()+
                    "cust_address="+et_owner_address.getText()+
                    "cust_contact="+et_owner_contact.getText()+
                    "cust_email="+et_owner_email.getText()+
                    "pet_name="+et_owner_pet_name.getText()+
                    "pet_species"+cb_species.getSelectedItem().toString()+
                    "pet_doe"+ Enum_Domestic_Exotic.Domestic.toString()+
                    "vet_name"+cb_vet.getSelectedItem().toString()+
                    "appointment_date"+obDataFormat.format(jdc_appointment.getDate())+
                    "appointment_time_start"+cb_time_start.getSelectedItem().toString()+
                    "appointment_time_start"+cb_time_end.getSelectedItem().toString()+
                    "WHERE ID="+id_selected;
                query(sql);
            }else{
                String sql="Update AppointmentTable set cust_first_name="+et_owner_first_name.getText()+
                    "cust_last_name="+et_owner_last_name.getText()+
                    "cust_address="+et_owner_address.getText()+
                    "cust_contact="+et_owner_contact.getText()+
                    "cust_email="+et_owner_email.getText()+
                    "pet_name="+et_owner_pet_name.getText()+
                    "pet_species"+cb_species.getSelectedItem().toString()+
                    "pet_doe"+ Enum_Domestic_Exotic.Exotic.toString()+
                    "vet_name"+cb_vet.getSelectedItem().toString()+
                    "appointment_date"+obDataFormat.format(jdc_appointment.getDate())+
                    "appointment_time_start"+cb_time_start.getSelectedItem().toString()+
                    "appointment_time_start"+cb_time_end.getSelectedItem().toString()+
                    "WHERE ID="+id_selected;
                query(sql);
            }
            isEdit=false;
            this.setVisible(false);
        }else{
            String sql="SELECT TOP 1 ID FROM AppointmentTable ORDER BY ID DESC";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){id=rs.getInt("ID");}
            }catch(Exception e){
                
            }
            
            if(cb_domestic.isSelected()&&cb_exotic.isSelected()){
                JOptionPane.showMessageDialog(null,"Error creating appointment.");
            }else if(cb_domestic.isSelected()){
                id++;
                Appointment appointment= new Appointment(id,et_owner_first_name.getText(), et_owner_last_name.getText(), 
                    et_owner_address.getText(), et_owner_contact.getText(), et_owner_email.getText(), 
                    et_owner_pet_name.getText(), Enum_Species.valueOf(cb_species.getSelectedItem().toString()),
                    Enum_Domestic_Exotic.Domestic, cb_vet.getSelectedItem().toString(),
                    jdc_appointment.getDate(), cb_time_start.getSelectedItem().toString());
                insertToTable(Enum_Domestic_Exotic.Domestic.toString(),cb_species.getSelectedItem().toString());
            }else if (cb_exotic.isSelected()){
                id++;
                Appointment appointment= new Appointment(id,et_owner_first_name.getText(), et_owner_last_name.getText(), 
                    et_owner_address.getText(), et_owner_contact.getText(), et_owner_email.getText(), 
                    et_owner_pet_name.getText(), Enum_Species.valueOf(cb_species.getSelectedItem().toString()),
                    Enum_Domestic_Exotic.Exotic, cb_vet.getSelectedItem().toString(),
                    jdc_appointment.getDate(), cb_time_start.getSelectedItem().toString());
                insertToTable(Enum_Domestic_Exotic.Exotic.toString(),cb_species.getSelectedItem().toString());             
            }else{
                JOptionPane.showMessageDialog(null,"Error creating appointment.");
            }
        }
    }//GEN-LAST:event_btn_done_appointmentMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn=Connect.connectDB();
        if(isEdit==true){loadData();}
    }//GEN-LAST:event_formWindowOpened

    private void query(String sql){
        try{
                pst=conn.prepareStatement(sql);
                pst.executeUpdate();
            }catch(Exception e){
                
            }
    }
    
    public void insertToTable(String doe, String species){
        String sql="INSERT INTO AppointmentTable VALUES("+
                        id+",'"+
                        et_owner_first_name.getText()+"','"+
                        et_owner_last_name.getText()+"','"+
                        et_owner_address.getText()+"','"+
                        et_owner_contact.getText()+"','"+
                        et_owner_email.getText()+"','"+
                        et_owner_pet_name.getText()+"','"+
                        species+"','"+
                        doe+"','"+
                        cb_vet.getSelectedItem().toString()+"','"+
                        obDataFormat.format(jdc_appointment.getDate())+"','"+
                        cb_time_start.getSelectedItem().toString()+"','"+
                        cb_time_end.getSelectedItem().toString()+"')";
        try{
        pst=conn.prepareStatement(sql);
        pst.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void setID(String id){
        id_selected=id;
        isEdit=true;
    }
    
    public void loadData(){
        String sql="SELECT * FROM AppointmentTable WHERE ID = "+id_selected;
        try{
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            
            if(rs.next()){
            et_owner_first_name.setText(rs.getString("cust_first_name"));
            et_owner_last_name.setText(rs.getString("cust_last_name"));
            et_owner_address.setText(rs.getString("cust_address"));
            et_owner_contact.setText(rs.getString("cust_contact"));
            et_owner_email.setText(rs.getString("cust_email"));
            et_owner_pet_name.setText(rs.getString("pet_name"));
            cb_species.setSelectedItem(rs.getString("pet_species"));
            if(rs.getString("pet_doe").equals("Domestic")){
                cb_domestic.setSelected(true);
            }else{
                cb_exotic.setSelected(true);    
            }
            cb_vet.setSelectedItem(rs.getString("vet_name"));
            jdc_appointment.setDate(obDataFormat.parse(rs.getString("appointment_date")));
            cb_time_start.setSelectedItem(rs.getString("appointment_time_start"));
            cb_time_end.setSelectedItem(rs.getString("appointment_time_end"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error.");
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Create_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Create_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Create_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Receptionist_Create_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Receptionist_Create_Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_done_appointment;
    private javax.swing.JCheckBox cb_domestic;
    private javax.swing.JCheckBox cb_exotic;
    private javax.swing.JComboBox cb_pet_gender;
    private javax.swing.JComboBox cb_species;
    private javax.swing.JComboBox cb_time_end;
    private javax.swing.JComboBox cb_time_start;
    private javax.swing.JComboBox cb_vet;
    private javax.swing.JTextField et_owner_address;
    private javax.swing.JTextField et_owner_contact;
    private javax.swing.JTextField et_owner_email;
    private javax.swing.JTextField et_owner_first_name;
    private javax.swing.JTextField et_owner_last_name;
    private javax.swing.JTextField et_owner_pet_name;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdc_appointment;
    // End of variables declaration//GEN-END:variables
}
